### ISSUE TITLE
<switchableControllerActions> lead to #1313855173: The controller ".." is not allowed by this plugin

### ISSUE THREAD

**Issue by TrueType** [helhum/typoscript_rendering#9] opened 2015-08-18 10:33 UTC
Hi Helmut,
we found our requests not working with a plugin configured with flexforms and switchableControllerActions. The error description here https://wiki.typo3.org/Exception/CMS/1313855173 gave a hint on the source of the problem.
Henri

**Comment by helhum** [comment] 2015-08-18 10:35
So what exactly is your problem then?

**Comment by TrueType** [comment] 2015-08-18 10:41
Well. If you have a plugin, whos actions are configured using flexforms, you won't be able to use your helper to generate Ajax calls. You may still set a different contextRecord param, though. Or drop the flexform configuration as we will probably do. I cannot say how popular switchableControllerActions are. And again, the problem may depend on a situation, where you call from one extension to another as we do. Just wanted to give you that feedback as it took us a while to figure it out.

**Comment by helhum** [comment] 2015-08-18 10:53
Thanks for the report.

Well, it has nothing to do with my view helper, right? If you'd generate action links to disallowed actions with the regular view helper, it would fail as well, right? So if you need (ajax) links to certain actions **and** use switchableControllerActions, you must allow these actions in the configuration.

I'll close this now. But maybe it helps others to more quickly identify such an issue with their configuration.

**Comment by TrueType** [comment] 2015-08-18 11:08
Haha. Actually this is the funny thing about this issue. I am creating links with extension A with plugin x to call plugin y of extension B. So Ax->By this is. The flexform configuration is with x, though! As I said, it depends on the contextRecord.

**Comment by helhum** [comment] 2015-08-18 11:11
>  I am creating links with extension A with plugin x to call plugin y of extension B. So Ax->By this is. 

And this does work with the regular action link view helper?

**Comment by TrueType** [comment] 2015-08-18 11:28
I checked. The regular action link view helper works.

**Comment by helhum** [comment] 2015-08-18 12:44
Hm, OK. So worth looking into that.

Thanks!

**Comment by mischka** [comment] 2015-09-14 13:33
Yes I agree the problem is the current default context, if you want to load a other extension

**Comment by helhum** [comment] 2016-05-09 16:09
> I am creating links with extension A with plugin x to call plugin y of extension B. So Ax->By this is. The flexform configuration is with x, though! 

OK, sure. I finally understood the issue :)

> As I said, it depends on the contextRecord

Exactly correct. I don't see any possibility to solve this automatically, except defaulting to page if you link to another plugin.

> Maybe a fallback to the current page is a solution.

So yes, @mischka I will do so.

**Closed** 2016-05-09 20:33 UTC
